# Generated by Django 4.1.6 on 2023-02-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ticket_ticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_company',
            field=models.CharField(default='NON', max_length=3),
        ),
    ]
