# Generated by Django 4.1.6 on 2023-02-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ticket_ticket_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(choices=[('SUP', 'Support'), ('KTN', 'Koton'), ('LCW', 'LcWaikiki'), ('DFC', 'DeFacto'), ('CLS', "Colin's")], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_company',
            field=models.ForeignKey(default='NON', on_delete=django.db.models.deletion.CASCADE, to='main.profile', to_field='company'),
        ),
    ]
