# Generated by Django 4.1.6 on 2023-02-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_ticket_ticket_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(choices=[('SUP', 'Support'), ('KTN', 'Koton'), ('LCW', 'LcWaikiki'), ('DFC', 'DeFacto'), ('CLS', "Colin's")], max_length=3),
        ),
    ]
