# Generated by Django 4.1.6 on 2023-02-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
