# Generated by Django 4.1.6 on 2023-02-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_profile_company_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solved_status',
            field=models.BooleanField(default=False),
        ),
    ]
