# Generated by Django 4.1.6 on 2023-02-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rename_solved_by_user_ticket_solved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='solved_status',
            new_name='status',
        ),
    ]
