# Generated by Django 4.1.6 on 2023-02-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='country',
            field=models.CharField(blank=True, choices=[('RU', 'Russia'), ('KZ', 'Kazakhstan'), ('MK', 'Macedonia'), ('RO', 'Romania'), ('UZ', 'Uzbekistan')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('RU', 'Russia'), ('KZ', 'Kazakhstan'), ('MK', 'Macedonia'), ('RO', 'Romania'), ('UZ', 'Uzbekistan')], max_length=3),
        ),
    ]
