# Generated by Django 4.1.6 on 2023-02-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_ticket_country_alter_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
